pool:
  vmImage: ubuntu-22.04

steps:
- task: UseDotNet@2
  displayName: 'Install .NET9'
  inputs:
    packageType: 'sdk'
    version: '9.x'
    includePreviewVersions: false

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'restore'
#     feedsToUse: 'config'

- script: dotnet --list-sdks

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Courses.sln'
    arguments: '-c Release'
  displayName: 'Build .NET'